version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      args:
        - BUILD_VERSION=${GITHUB_SHA}
    container_name: nest-telegram-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
